Hercules: src/hw/led.cpp File Reference
led.cpp File Reference
#include <mbed.h>
#include "hw/led.h"
Functions
DigitalOut led1 (ONBOARD_LED)
DigitalOut led2 (EXTERNAL_LED)
int SwitchPin (PinName Pin, bool OnOff)
Sets Pin state.
void LED ()
LED Constructor.
int On (PinName Pin)
Set Pin to On, returns 0 when successful - 1 when not.
int Off (PinName Pin)
Set Pin to Off, returns 0 when successful - 1 when not.
Function Documentation
LED()
void LED ()
LED Constructor.
Definition at line 41 of file led.cpp.
 {};
led1()
DigitalOut led1 (ONBOARD_LED)
Referenced by SwitchPin().
led2()
DigitalOut led2 (EXTERNAL_LED)
Referenced by SwitchPin().
Off()
int Off (PinName Pin)
Set Pin to Off, returns 0 when successful - 1 when not.
Parameters
Pin
Returns
int
Definition at line 60 of file led.cpp.
 {
     return SwitchPin(Pin, 0);
 }
References SwitchPin().
On()
int On (PinName Pin)
Set Pin to On, returns 0 when successful - 1 when not.
Parameters
Pin
Returns
int
Definition at line 49 of file led.cpp.
 {
     return SwitchPin(Pin, 1);
 };
References SwitchPin().
SwitchPin()
int SwitchPin (PinName Pin, bool OnOff)
Sets Pin state.
Parameters
Pin
OnOff
Definition at line 16 of file led.cpp.
 {
     switch (Pin)
     {
     case ONBOARD_LED:
         led1 = OnOff;
         return 0;
     case EXTERNAL_LED:
         led2 = OnOff;
         return 0;
     default:
         return 1;
     }
     return 1;
 };
References EXTERNAL_LED, led1(), led2(), and ONBOARD_LED.
Referenced by Off(), and On().