Hercules: src/main.cpp File Reference
main.cpp File Reference
#include <mbed.h>
#include "LCD_DISCO_F746NG.h"
#include "TS_DISCO_F746NG.h"
#include "DHT.h"
#include "display.h"
#include <iostream>
#include "stm32746g_discovery_sd.h"
#include "stm32746g_discovery_sdram.h"
#include "rtos.h"
#include "FileSystem.h"
Functions
Serial usbCom (USBTX, USBRX)
DigitalOut led1 (LED1)
DigitalOut led2 (D2)
DigitalOut buzzer (D4)
DHT dhtSensor (A0, SEN51035P)
AnalogIn vibrationSensor (A1)
AnalogIn lightSensor (A2)
AnalogIn soundSensor (A3)
void counterTick ()
Increases the current count or resets when counter_max is hit.
void clearDisplay ()
Clears the main display & sets default colors.
int earthQuakeDetected ()
Detects earth quakes. Sets the red led to ON/OFF.
void displayCurrentHT ()
Displays temperature & humidity (humidity)
void displayLightStatus ()
Says "godnat" when dark, "goddag" when light.
void noiseWarning ()
Displays a warning when the noise is too much.
void displayEarthQuakeStatus ()
Displays current earthquake status.
void drawButton (uint16_t xPos, u_int16_t yPos, uint8_t *Text, int dia=10, int xOffset=5, int yOffset=7)
bool buttonHit (uint16_t xPos, uint16_t yPos, uint16_t cursor_x, uint16_t cursor_y, uint16_t hitBoxAera=20)
Checks if a button has been hit.
void deviceSetup ()
Initial device setup view.
void counter_thread ()
Counter task.
void view1 ()
View 1 logic.
void view2 ()
View 2 logic.
void setView (int viewNumber)
Set the View object.
void switchView ()
Switches the current view.
void boot ()
Setup for app.
void gui_thread ()
Gui Thread.
int main ()
Application entry point.
Variables
LCD_DISCO_F746NG lcd
TS_DISCO_F746NG ts
int currentView = 1
int viewCount = 2
int tempScale = 0
TS_StateTypeDef TS_State
uint16_t x
uint16_t y
uint8_t text [30]
uint8_t status
uint8_t idx
uint8_t cleared = 0
uint8_t prev_nb_touches = 0
int counter_max = 9999
int counter_current = 0
int roomNumber
int buildingNumber
Thread noiseThread
bool noiseThreadStarted = false
int device_setup_building_no = 0
int device_setup_room_no = 0
Thread counterThread
bool counterThreadStarted = false
Thread guiThread
Function Documentation
boot()
void boot ()
Setup for app.
Definition at line 534 of file main.cpp.
 {
   led1 = 1;
   lcd.Init();
   buzzer = 0;
   //uint8_t *image = (uint8_t *)fallout;
   //lcd.DrawBitmap(0, 0, image);
   lcd.DisplayStringAt(0, LINE(1), (uint8_t *)"Booting Hercules...", CENTER_MODE);
   lcd.DisplayStringAt(0, LINE(4), (uint8_t *)"Please wait", CENTER_MODE);
   if (BSP_SD_IsDetected())
   {
     BSP_SD_Init();
     lcd.DisplayStringAt(0, LINE(6), (uint8_t *)"SD Card detected", CENTER_MODE);
   }
   else
   {
     lcd.DisplayStringAt(0, LINE(6), (uint8_t *)"SD Card not detected", CENTER_MODE);
   }
   wait(1.0f);
   clearDisplay();
 }
References buzzer(), clearDisplay(), lcd, and led1().
Referenced by main().
buttonHit()
bool buttonHit (uint16_t xPos, uint16_t yPos, uint16_t cursor_x, uint16_t cursor_y, uint16_t hitBoxAera = 20)
Checks if a button has been hit.
Parameters
xPos
yPos
cursor_x
cursor_y
hitBoxAera
Returns
true
false
Definition at line 253 of file main.cpp.
 {
   int y_hitbox_min = yPos - hitBoxAera;
   int y_hitbox_max = yPos + hitBoxAera;
   int x_hitbox_min = xPos - hitBoxAera;
   int x_hitbox_max = xPos + hitBoxAera;
   if ((cursor_y >= y_hitbox_min && cursor_y <= y_hitbox_max) && (cursor_x >= x_hitbox_min && cursor_x <= x_hitbox_max))
   {
     return true;
   }
   return false;
 }
Referenced by deviceSetup(), and view2().
buzzer()
DigitalOut buzzer (D4)
Referenced by boot().
clearDisplay()
void clearDisplay ()
Clears the main display & sets default colors.
Definition at line 86 of file main.cpp.
 {
   for (int i = 0; i <= 10; i++)
   {
     lcd.DisplayStringAt(0, LINE(i), (uint8_t *)"                         ", LEFT_MODE);
     lcd.DisplayStringAt(0, LINE(i), (uint8_t *)"                         ", CENTER_MODE);
     lcd.DisplayStringAt(0, LINE(i), (uint8_t *)"                         ", RIGHT_MODE);
     lcd.ClearStringLine(i);
   }
   lcd.Clear(LCD_BACKGROUND);
   lcd.SetBackColor(LCD_TEXT_BACKGROUND);
   lcd.SetTextColor(LCD_TEXT_COLOR);
 }
References lcd, LCD_BACKGROUND, LCD_TEXT_BACKGROUND, and LCD_TEXT_COLOR.
Referenced by boot(), gui_thread(), and setView().
counter_thread()
void counter_thread ()
Counter task.
Definition at line 365 of file main.cpp.
 {
   while (counterThreadStarted)
   {
     counterTick();
     ThisThread::sleep_for(1000);
   }
 }
References counterThreadStarted, and counterTick().
Referenced by view1().
counterTick()
void counterTick ()
Increases the current count or resets when counter_max is hit.
Definition at line 59 of file main.cpp.
 {
   if (counter_current <= counter_max)
   {
     counter_current++;
     if (counter_current == counter_max)
     {
       counter_current = 0;
     }
   }
   char display_int[32];
   sprintf(display_int, "Count: %04u", counter_current);
   if (1 == currentView)
   {
     lcd.DisplayStringAt(0, LINE(4), (uint8_t *)display_int, CENTER_MODE);
   }
 }
References counter_current, counter_max, currentView, and lcd.
Referenced by counter_thread().
deviceSetup()
void deviceSetup ()
Initial device setup view.
Definition at line 273 of file main.cpp.
 {
   char str_building[32];
   char str_room[32];
   sprintf(str_building, "Building: %d", device_setup_building_no);
   sprintf(str_room, "Room: %d", device_setup_room_no);
   lcd.DisplayStringAt(125, 75, (uint8_t *)str_building, LEFT_MODE);
   lcd.DisplayStringAt(125, 150, (uint8_t *)str_room, LEFT_MODE);
   // Building adjustment
   uint16_t building_incr_xPos = 300;
   uint16_t building_incr_yPos = 80;
   drawButton(building_incr_xPos, building_incr_yPos, (uint8_t *)"+");
   uint16_t building_decr_xPos = 350;
   uint16_t building_decr_yPos = 80;
   drawButton(building_decr_xPos, building_decr_yPos, (uint8_t *)"-");
   // Room adjustment
   uint16_t room_incr_xPos = 300;
   uint16_t room_incr_yPos = 155;
   drawButton(room_incr_xPos, room_incr_yPos, (uint8_t *)"+");
   uint16_t room_decr_xPos = 350;
   uint16_t room_decr_yPos = 155;
   drawButton(room_decr_xPos, room_decr_yPos, (uint8_t *)"-");
   // Save button
   uint16_t save_btn_xPos = 240;
   uint16_t save_btn_yPos = 230;
   drawButton(save_btn_xPos, save_btn_yPos, (uint8_t *)"Save", 32, 22);
   ts.GetState(&TS_State);
   if (TS_State.touchDetected)
   {
     for (idx = 0; idx < TS_State.touchDetected; idx++)
     {
       x = TS_State.touchX[idx];
       y = TS_State.touchY[idx];
       // Building adjustment
       if (buttonHit(building_incr_xPos, building_incr_yPos, x, y))
       {
         device_setup_building_no++;
         wait(0.5f);
       }
       if (buttonHit(building_decr_xPos, building_decr_yPos, x, y))
       {
         device_setup_building_no--;
         wait(0.5f);
       }
       // Room adjustment
       if (buttonHit(room_incr_xPos, room_incr_yPos, x, y))
       {
         device_setup_room_no++;
         wait(0.5f);
       }
       if (buttonHit(room_decr_xPos, room_incr_yPos, x, y))
       {
         device_setup_room_no--;
         wait(0.5f);
       }
       if (buttonHit(save_btn_xPos, save_btn_yPos, x, y))
       {
         buildingNumber = device_setup_building_no;
         roomNumber = device_setup_room_no;
         wait(0.5f);
         cleared = false;
       }
     }
   }
 }
References buildingNumber, buttonHit(), cleared, device_setup_building_no, device_setup_room_no, drawButton(), idx, lcd, roomNumber, ts, TS_State, x, and y.
Referenced by gui_thread().
dhtSensor()
DHT dhtSensor (A0 , SEN51035P)
Referenced by displayCurrentHT().
displayCurrentHT()
void displayCurrentHT ()
Displays temperature & humidity (humidity)
Definition at line 127 of file main.cpp.
 {
   int error = 0;
   float h = 0.0f, c = 0.0f, d = 0.0f;
   error = dhtSensor.readData();
   if (0 == error)
   {
     c = dhtSensor.ReadTemperature((eScale)tempScale);
     h = dhtSensor.ReadHumidity();
     d = dhtSensor.CalcdewPointFast(c, h);
     char temp[32];
     char tempScaleSymbol[8];
     char humid[32];
     char dew_point[32];
     switch (tempScale)
     {
     case 0:
       sprintf(tempScaleSymbol, "C");
       break;
     case 1:
       sprintf(tempScaleSymbol, "F");
       break;
     case 2:
       sprintf(tempScaleSymbol, "K");
       break;
     default:
       sprintf(tempScaleSymbol, "C");
       break;
     }
     sprintf(temp, "Temperature: %d %s", (int)c, tempScaleSymbol);
     sprintf(humid, "Humidity: %d %%", (int)h);
     sprintf(dew_point, "Dew Point: %d %s", (int)d, tempScaleSymbol);
     lcd.DisplayStringAt(0, LINE(6), (uint8_t *)temp, CENTER_MODE);
     lcd.DisplayStringAt(0, LINE(7), (uint8_t *)humid, CENTER_MODE);
     lcd.DisplayStringAt(0, LINE(8), (uint8_t *)dew_point, CENTER_MODE);
   }
 }
References dhtSensor(), lcd, and tempScale.
Referenced by view1().
displayEarthQuakeStatus()
void displayEarthQuakeStatus ()
Displays current earthquake status.
Definition at line 221 of file main.cpp.
 {
   char earth_quake[32];
   sprintf(earth_quake, "Is Earthquake: %d", earthQuakeDetected());
   lcd.DisplayStringAt(0, LINE(10), (uint8_t *)earth_quake, CENTER_MODE);
 }
References earthQuakeDetected(), and lcd.
Referenced by view1().
displayLightStatus()
void displayLightStatus ()
Says "godnat" when dark, "goddag" when light.
Definition at line 175 of file main.cpp.
 {
   float luminence = lightSensor.read();
   if (luminence < 0.3)
   {
     lcd.DisplayStringAt(0, LINE(12), (uint8_t *)"Godnat", CENTER_MODE);
   }
   else
   {
     lcd.DisplayStringAt(0, LINE(12), (uint8_t *)"Goddag", CENTER_MODE);
   }
 }
References lcd, and lightSensor().
Referenced by view1().
drawButton()
void drawButton (uint16_t xPos, u_int16_t yPos, uint8_t * Text, int dia = 10, int xOffset = 5, int yOffset = 7)
Definition at line 234 of file main.cpp.
 {
   lcd.DrawCircle(xPos, yPos, dia);
   lcd.SetBackColor(LCD_BACKGROUND);
   lcd.DisplayStringAt((xPos - xOffset), (yPos - yOffset), Text, LEFT_MODE);
   lcd.SetBackColor(LCD_TEXT_BACKGROUND);
 }
References lcd, LCD_BACKGROUND, and LCD_TEXT_BACKGROUND.
Referenced by deviceSetup(), and view2().
earthQuakeDetected()
int earthQuakeDetected ()
Detects earth quakes. Sets the red led to ON/OFF.
Returns
int
Definition at line 109 of file main.cpp.
 {
   if (vibrationSensor.read() > 0.06)
   {
     led2 = 1;
     return 1;
   }
   led2 = 0;
   return 0;
 }
References led2(), and vibrationSensor().
Referenced by displayEarthQuakeStatus().
gui_thread()
void gui_thread ()
Gui Thread.
Definition at line 565 of file main.cpp.
 {
   while (true)
   {
     if (!buildingNumber && !roomNumber)
     {
       deviceSetup();
     }
     else
     {
       setView(currentView);
     }
     ts.GetState(&TS_State);
     if (buildingNumber && roomNumber && TS_State.touchDetected)
     {
       for (idx = 0; idx < TS_State.touchDetected; idx++)
       {
         x = TS_State.touchX[idx];
         y = TS_State.touchY[idx];
         int y_hitbox_min = 240 - 50;
         int y_hitbox_max = 240 + 50;
         int x_hitbox_min = 410 - 50;
         int x_hitbox_max = 410 + 50;
         if ((y >= y_hitbox_min && y <= y_hitbox_max) && (x >= x_hitbox_min && x <= x_hitbox_max))
         {
           switchView();
         }
       }
     }
     else
     {
       if (!cleared)
       {
         clearDisplay();
         char displayView[32];
         sprintf(displayView, "View: %d", currentView);
         lcd.DrawHLine(10, 10, 460);
         lcd.SetFont(&Font8);
         lcd.SetBackColor(LCD_BACKGROUND);
         lcd.DisplayStringAt(10, 12, (uint8_t *)"Hercules v1.1", LEFT_MODE);
         lcd.DrawVLine(80, 10, 11);
         if (buildingNumber && roomNumber)
         {
           char building[32];
           char room[32];
           sprintf(building, "Building: %d", buildingNumber);
           sprintf(room, "Room: %d", roomNumber);
           lcd.DisplayStringAt(85, 12, (uint8_t *)building, LEFT_MODE);
           lcd.DisplayStringAt(150, 12, (uint8_t *)room, LEFT_MODE);
         }
         lcd.SetBackColor(LCD_TEXT_BACKGROUND);
         lcd.DrawHLine(10, 20, 460);
         lcd.SetFont(&Font16);
         if (buildingNumber && roomNumber)
         {
           lcd.DisplayStringAt(10, 240, (uint8_t *)displayView, LEFT_MODE);
           lcd.DisplayStringAt(410, 240, (uint8_t *)"Next", LEFT_MODE);
         }
         cleared = 1;
       }
     }
   }
 }
References buildingNumber, clearDisplay(), cleared, currentView, deviceSetup(), idx, lcd, LCD_BACKGROUND, LCD_TEXT_BACKGROUND, roomNumber, setView(), switchView(), ts, TS_State, x, and y.
Referenced by main().
led1()
DigitalOut led1 (LED1)
Referenced by boot().
led2()
DigitalOut led2 (D2)
Referenced by earthQuakeDetected().
lightSensor()
AnalogIn lightSensor (A2)
Referenced by displayLightStatus().
main()
int main ()
Application entry point.
Returns
int
Definition at line 650 of file main.cpp.
 {
   boot();
   // The data cache is disabled to avoid screen flickering.
   SCB_CleanDCache();
   SCB_DisableDCache();
   wait(0.25);
   guiThread.start(gui_thread);
 }
References boot(), gui_thread(), and guiThread.
noiseWarning()
void noiseWarning ()
Displays a warning when the noise is too much.
Definition at line 196 of file main.cpp.
 {
   while (noiseThreadStarted)
   {
     float noiseLevel = soundSensor.read();
     if (noiseLevel >= 0.35 && 1 == currentView)
     {
       lcd.DisplayStringAt(0, LINE(13), (uint8_t *)"Noise warning!", CENTER_MODE);
     }
     else
     {
       lcd.SetBackColor(LCD_BACKGROUND);
       lcd.DisplayStringAt(0, LINE(13), (uint8_t *)"              ", CENTER_MODE);
       lcd.SetBackColor(LCD_TEXT_BACKGROUND);
     }
     ThisThread::sleep_for(1000);
   }
 }
References currentView, lcd, LCD_BACKGROUND, LCD_TEXT_BACKGROUND, noiseThreadStarted, and soundSensor().
Referenced by view1().
setView()
void setView (int viewNumber)
Set the View object.
Parameters
viewNumber
Definition at line 474 of file main.cpp.
 {
   if (viewNumber != currentView)
   {
     usbCom.printf("[Toggle]: setView viewNumber %d!\n", viewNumber);
     usbCom.printf("[Toggle]: setView currentView %d!\n", currentView);
     cleared = 0;
     clearDisplay();
   }
   currentView = viewNumber;
   switch (viewNumber)
   {
   case 1:
     view1();
     break;
   case 2:
     view2();
     break;
   default:
     usbCom.printf("Unknown view number: %d\n", viewNumber);
     break;
   }
 }
References clearDisplay(), cleared, currentView, usbCom(), view1(), and view2().
Referenced by gui_thread(), and switchView().
soundSensor()
AnalogIn soundSensor (A3)
Referenced by noiseWarning().
switchView()
void switchView ()
Switches the current view.
Definition at line 507 of file main.cpp.
 {
   wait(0.1);
   usbCom.printf("switchView toggled!\n");
   int viewNumber = currentView;
   if (currentView < viewCount)
   {
     viewNumber++;
   }
   else
   {
     viewNumber = 1;
   }
   usbCom.printf("switchView viewNumber %d!\n", viewNumber);
   usbCom.printf("switchView currentView %d!\n", currentView);
   setView(viewNumber);
 }
References currentView, setView(), usbCom(), and viewCount.
Referenced by gui_thread().
usbCom()
Serial usbCom (USBTX , USBRX)
Referenced by setView(), switchView(), and view2().
vibrationSensor()
AnalogIn vibrationSensor (A1)
Referenced by earthQuakeDetected().
view1()
void view1 ()
View 1 logic.
Definition at line 379 of file main.cpp.
 {
   displayCurrentHT();
   displayEarthQuakeStatus();
   displayLightStatus();
   if (!counterThreadStarted)
   {
     counterThread.start(counter_thread);
     counterThreadStarted = true;
   }
   if (!noiseThreadStarted)
   {
     noiseThread.start(noiseWarning);
     noiseThreadStarted = true;
   }
 }
References counter_thread(), counterThread, counterThreadStarted, displayCurrentHT(), displayEarthQuakeStatus(), displayLightStatus(), noiseThread, noiseThreadStarted, and noiseWarning().
Referenced by setView().
view2()
void view2 ()
View 2 logic.
Definition at line 404 of file main.cpp.
 {
   char i2c_clock[32];
   sprintf(i2c_clock, "I2C Clock: %d KHz", ((int)I2C_SPEED / 1000));
   lcd.DisplayStringAt(0, LINE(3), (uint8_t *)i2c_clock, CENTER_MODE);
   if (BSP_SD_IsDetected())
   {
     lcd.DisplayStringAt(0, LINE(7), (uint8_t *)"SD Card detected", CENTER_MODE);
   }
   else
   {
     lcd.DisplayStringAt(0, LINE(7), (uint8_t *)"SD Card not detected", CENTER_MODE);
   }
   lcd.DisplayStringAt(145, 150, (uint8_t *)"Temperature scale", LEFT_MODE);
   uint16_t tempBtnYpos = 190;
   uint16_t tempBtnCelsiusPos = 170;
   uint16_t tempBtnFahrenheitPos = 230;
   uint16_t tempBtnKelvinPos = 290;
   drawButton(tempBtnCelsiusPos, tempBtnYpos, (uint8_t *)"C");
   drawButton(tempBtnFahrenheitPos, tempBtnYpos, (uint8_t *)"F");
   drawButton(tempBtnKelvinPos, tempBtnYpos, (uint8_t *)"K");
   ts.GetState(&TS_State);
   if (TS_State.touchDetected)
   {
     for (idx = 0; idx < TS_State.touchDetected; idx++)
     {
       x = TS_State.touchX[idx];
       y = TS_State.touchY[idx];
       // Building adjustment
       if (buttonHit(tempBtnCelsiusPos, tempBtnYpos, x, y))
       {
         tempScale = 0;
         usbCom.printf("Temp scale switched to Celcius!");
         wait(0.5f);
       }
       if (buttonHit(tempBtnFahrenheitPos, tempBtnYpos, x, y))
       {
         tempScale = 1;
         usbCom.printf("Temp scale switched to Fahrenheit!");
         wait(0.5f);
       }
       if (buttonHit(tempBtnKelvinPos, tempBtnYpos, x, y))
       {
         tempScale = 2;
         usbCom.printf("Temp scale switched to Kelvin!");
         wait(0.5f);
       }
     }
   }
 }
References buttonHit(), drawButton(), idx, lcd, tempScale, ts, TS_State, usbCom(), x, and y.
Referenced by setView().
Variable Documentation
buildingNumber
int buildingNumber
Definition at line 53 of file main.cpp.
Referenced by deviceSetup(), and gui_thread().
cleared
uint8_t cleared = 0
Definition at line 45 of file main.cpp.
Referenced by deviceSetup(), gui_thread(), and setView().
counter_current
int counter_current = 0
Definition at line 50 of file main.cpp.
Referenced by counterTick().
counter_max
int counter_max = 9999
Definition at line 49 of file main.cpp.
Referenced by counterTick().
counterThread
Thread counterThread
Definition at line 358 of file main.cpp.
Referenced by view1().
counterThreadStarted
bool counterThreadStarted = false
Definition at line 359 of file main.cpp.
Referenced by counter_thread(), and view1().
currentView
int currentView = 1
Definition at line 34 of file main.cpp.
Referenced by counterTick(), gui_thread(), noiseWarning(), setView(), and switchView().
device_setup_building_no
int device_setup_building_no = 0
Definition at line 231 of file main.cpp.
Referenced by deviceSetup().
device_setup_room_no
int device_setup_room_no = 0
Definition at line 232 of file main.cpp.
Referenced by deviceSetup().
guiThread
Thread guiThread
Definition at line 643 of file main.cpp.
Referenced by main().
idx
uint8_t idx
Definition at line 44 of file main.cpp.
Referenced by deviceSetup(), gui_thread(), and view2().
lcd
LCD_DISCO_F746NG lcd
Definition at line 16 of file main.cpp.
Referenced by boot(), clearDisplay(), counterTick(), deviceSetup(), displayCurrentHT(), displayEarthQuakeStatus(), displayLightStatus(), drawButton(), gui_thread(), noiseWarning(), and view2().
noiseThread
Thread noiseThread
Definition at line 189 of file main.cpp.
Referenced by view1().
noiseThreadStarted
bool noiseThreadStarted = false
Definition at line 190 of file main.cpp.
Referenced by noiseWarning(), and view1().
prev_nb_touches
uint8_t prev_nb_touches = 0
Definition at line 46 of file main.cpp.
roomNumber
int roomNumber
Definition at line 52 of file main.cpp.
Referenced by deviceSetup(), and gui_thread().
status
uint8_t status
Definition at line 43 of file main.cpp.
tempScale
int tempScale = 0
Definition at line 37 of file main.cpp.
Referenced by displayCurrentHT(), and view2().
text
uint8_t text[30]
Definition at line 42 of file main.cpp.
Referenced by Display::String().
ts
TS_DISCO_F746NG ts
Definition at line 18 of file main.cpp.
Referenced by deviceSetup(), gui_thread(), and view2().
TS_State
TS_StateTypeDef TS_State
Definition at line 40 of file main.cpp.
Referenced by deviceSetup(), gui_thread(), and view2().
viewCount
int viewCount = 2
Definition at line 35 of file main.cpp.
Referenced by switchView().
x
uint16_t x
Definition at line 41 of file main.cpp.
Referenced by deviceSetup(), gui_thread(), and view2().
y
uint16_t y
Definition at line 41 of file main.cpp.
Referenced by deviceSetup(), gui_thread(), and view2().