Hercules: src/hw/sensors.cpp File Reference
sensors.cpp File Reference
#include <stdlib.h>
#include <vector>
#include "sensors.h"
#include "DHT.h"
#include "rtos.h"
#include "cmsis_os.h"
#include "mbed.h"
Functions
DHT dhtSensor (A0, SEN51035P)
void dhtTaskContext (std::vector< u_int8_t > *dhtResult)
void dhtTask ()
osStatus startDhtTask ()
std::vector< u_int8_t > getDHT ()
void stopDht ()
AnalogIn vibrationSensor (A1)
void earthQuakeTaskContext (bool *earthQuakeRes)
Task Context for EarthQuake detection.
void earthQuakeTask ()
EarthQuake Task.
osStatus InitEarthQuakeDetection ()
EarthQuake Task Initializer.
Variables
Thread dhtThread
bool dhtThreadRunning = false
std::vector< u_int8_t > dhtResult
Thread earthQuakeThread
bool earthQuakeThreadRunning = false
bool isEarthQuake = false
Function Documentation
dhtSensor()
DHT dhtSensor (A0 , SEN51035P)
Referenced by dhtTaskContext().
dhtTask()
void dhtTask ()
Definition at line 55 of file sensors.cpp.
 {
     dhtTaskContext(&dhtResult);
 }
References dhtResult, and dhtTaskContext().
Referenced by startDhtTask().
dhtTaskContext()
void dhtTaskContext (std::vector< u_int8_t > * dhtResult)
Definition at line 18 of file sensors.cpp.
 {
     std::vector<u_int8_t> result;
     int error = 0;
     float h = 0.0f, c = 0.0f, d = 0.0f;
     dhtThreadRunning = true;
     while (true)
     {
         error = dhtSensor.readData();
         if (0 == error)
         {
             c = dhtSensor.ReadTemperature(CELCIUS);
             h = dhtSensor.ReadHumidity();
             d = dhtSensor.CalcdewPointFast(c, h);
             char temp[32];
             char humid[32];
             char dew_point[32];
             sprintf(temp, "Temperature: %d C", (int)c);
             sprintf(humid, "Humidity: %d %%", (int)h);
             sprintf(dew_point, "Dew Point: %d C", (int)d);
             result.push_back((u_int8_t &)temp);
             result.push_back((u_int8_t &)humid);
             result.push_back((u_int8_t &)dew_point);
             *dhtResult = result;
         }
         dhtThread.wait(1000);
     }
 }
References dhtResult, dhtSensor(), dhtThread, and dhtThreadRunning.
Referenced by dhtTask().
earthQuakeTask()
void earthQuakeTask ()
EarthQuake Task.
Definition at line 107 of file sensors.cpp.
 {
     earthQuakeTaskContext(&isEarthQuake);
 }
References earthQuakeTaskContext(), and isEarthQuake.
Referenced by InitEarthQuakeDetection().
earthQuakeTaskContext()
void earthQuakeTaskContext (bool * earthQuakeRes)
Task Context for EarthQuake detection.
Parameters
earthQuakeRes
Definition at line 88 of file sensors.cpp.
 {
     earthQuakeThreadRunning = true;
     while (true)
     {
         if (vibrationSensor.read() > 0.06)
         {
             *earthQuakeRes = true;
         }
         *earthQuakeRes = false;
     }
 }
References earthQuakeThreadRunning, and vibrationSensor().
Referenced by earthQuakeTask().
getDHT()
std::vector<u_int8_t> getDHT ()
Definition at line 65 of file sensors.cpp.
 {
     return dhtResult;
 }
References dhtResult.
InitEarthQuakeDetection()
osStatus InitEarthQuakeDetection ()
EarthQuake Task Initializer.
Definition at line 116 of file sensors.cpp.
 {
     if (!earthQuakeThreadRunning)
     {
         return earthQuakeThread.start(&earthQuakeTask);
     }
 }
References earthQuakeTask(), earthQuakeThread, and earthQuakeThreadRunning.
startDhtTask()
osStatus startDhtTask ()
Definition at line 60 of file sensors.cpp.
 {
     return dhtThread.start(dhtTask);
 }
References dhtTask(), and dhtThread.
stopDht()
void stopDht ()
Definition at line 70 of file sensors.cpp.
 {
     dhtThread.terminate();
 }
References dhtThread.
vibrationSensor()
AnalogIn vibrationSensor (A1)
Referenced by earthQuakeTaskContext().
Variable Documentation
dhtResult
std::vector<u_int8_t> dhtResult
Definition at line 16 of file sensors.cpp.
Referenced by dhtTask(), dhtTaskContext(), and getDHT().
dhtThread
Thread dhtThread
Definition at line 14 of file sensors.cpp.
Referenced by dhtTaskContext(), startDhtTask(), and stopDht().
dhtThreadRunning
bool dhtThreadRunning = false
Definition at line 15 of file sensors.cpp.
Referenced by dhtTaskContext().
earthQuakeThread
Thread earthQuakeThread
Definition at line 79 of file sensors.cpp.
Referenced by InitEarthQuakeDetection().
earthQuakeThreadRunning
bool earthQuakeThreadRunning = false
Definition at line 80 of file sensors.cpp.
Referenced by earthQuakeTaskContext(), and InitEarthQuakeDetection().
isEarthQuake
bool isEarthQuake = false
Definition at line 81 of file sensors.cpp.
Referenced by earthQuakeTask().